export type Track = { id: string; title: string; url: string; platform: 'soundcloud' };

export const tracks: Track[] = [
  { id: "stop-drop-rock-rock-ft", title: "Stop Drop Rock Rock Ft", url: "https://soundcloud.com/1takequan/stop-drop-rock-rock-ft", platform: 'soundcloud' },
  { id: "runaway-ft-b23min-gom3z-prod", title: "Runaway FT B23min Gom3z PROD", url: "https://soundcloud.com/1takequan/runaway-ft-b23min-gom3z-prod", platform: 'soundcloud' },
  { id: "you-ft-bennyave-prod-by", title: "You FT Bennyave PROD By", url: "https://soundcloud.com/1takequan/you-ft-bennyave-prod-by", platform: 'soundcloud' },
  { id: "lesson-learned-ft-tyler-j", title: "Lesson Learned FT Tyler J", url: "https://soundcloud.com/1takequan/lesson-learned-ft-tyler-j", platform: 'soundcloud' },
  { id: "lunch-date-prod-by-slapmafia", title: "Lunch Date PROD By Slapmafia", url: "https://soundcloud.com/1takequan/lunch-date-prod-by-slapmafia", platform: 'soundcloud' },
  { id: "handful-prod-by-bigg-boo", title: "Handful PROD By Bigg Boo", url: "https://soundcloud.com/1takequan/handful-prod-by-bigg-boo", platform: 'soundcloud' },
  { id: "oowee-prod-by-flyguyy", title: "Oowee PROD By Flyguyy", url: "https://soundcloud.com/1takequan/oowee-prod-by-flyguyy", platform: 'soundcloud' },
  { id: "diddy-bop-ft-1taketeezy", title: "Diddy Bop FT 1taketeezy", url: "https://soundcloud.com/1takequan/diddy-bop-ft-1taketeezy", platform: 'soundcloud' },
  { id: "the-one-ft-1taketeezy-prod-by", title: "The One FT 1taketeezy PROD By", url: "https://soundcloud.com/1takequan/the-one-ft-1taketeezy-prod-by", platform: 'soundcloud' },
  { id: "embarrsed-prod-by-1-of-1", title: "Embarrsed PROD By 1 Of 1", url: "https://soundcloud.com/1takequan/embarrsed-prod-by-1-of-1", platform: 'soundcloud' },
  { id: "make-sense-prod-by-timmy-tunes", title: "Make Sense PROD By Timmy Tunes", url: "https://soundcloud.com/1takequan/make-sense-prod-by-timmy-tunes", platform: 'soundcloud' },
  { id: "buss-it", title: "Buss It", url: "https://soundcloud.com/1takequan/buss-it", platform: 'soundcloud' },
  { id: "anonymous", title: "Anonymous", url: "https://soundcloud.com/1takequan/anonymous", platform: 'soundcloud' },
  { id: "break-it", title: "Break It", url: "https://soundcloud.com/1takequan/break-it", platform: 'soundcloud' },
  { id: "major-league", title: "Major League", url: "https://soundcloud.com/1takequan/major-league", platform: 'soundcloud' },
  { id: "super", title: "Super", url: "https://soundcloud.com/1takequan/super", platform: 'soundcloud' },
  { id: "no-competition", title: "No Competition", url: "https://soundcloud.com/1takequan/no-competition", platform: 'soundcloud' },
  { id: "moneymaker", title: "Moneymaker", url: "https://soundcloud.com/1takequan/moneymaker", platform: 'soundcloud' },
  { id: "different", title: "Different", url: "https://soundcloud.com/1takequan/different", platform: 'soundcloud' },
  { id: "its-real", title: "Its Real", url: "https://soundcloud.com/1takequan/its-real", platform: 'soundcloud' },
  { id: "go-live-prod-by-killa-kam", title: "Go Live PROD By Killa Kam", url: "https://soundcloud.com/1takequan/go-live-prod-by-killa-kam", platform: 'soundcloud' },
  { id: "double-o-quan-prod-low-the", title: "Double O Quan PROD Low The", url: "https://soundcloud.com/1takequan/double-o-quan-prod-low-the", platform: 'soundcloud' },
  { id: "benny-x-quan", title: "Benny X Quan", url: "https://soundcloud.com/1takequan/benny-x-quan", platform: 'soundcloud' },
  { id: "3-sum-ft-lil-vada-donny-solo", title: "3 Sum FT Lil Vada Donny Solo", url: "https://soundcloud.com/1takequan/3-sum-ft-lil-vada-donny-solo", platform: 'soundcloud' },
  { id: "do-it-prod-by-scumbeatz", title: "Do It PROD By Scumbeatz", url: "https://soundcloud.com/1takequan/do-it-prod-by-scumbeatz", platform: 'soundcloud' },
  { id: "not-alot-prod-by-larrymakinallthehits", title: "Not Alot PROD By Larrymakinallthehits", url: "https://soundcloud.com/1takequan/not-alot-prod-by-larrymakinallthehits", platform: 'soundcloud' },
  { id: "tonight-ft-lil-vada-prod-by-crook", title: "Tonight FT Lil Vada PROD By Crook", url: "https://soundcloud.com/1takequan/tonight-ft-lil-vada-prod-by-crook", platform: 'soundcloud' },
  { id: "show-me-prod-bennyave", title: "Show Me PROD Bennyave", url: "https://soundcloud.com/1takequan/show-me-prod-bennyave", platform: 'soundcloud' },
  { id: "backshots-ft-boosie-badazz-1takejay-prod-by-420tiesto-killa-kam", title: "Backshots FT Boosie Badazz 1takejay PROD By 420tiesto Killa Kam", url: "https://soundcloud.com/1takequan/backshots-ft-boosie-badazz-1takejay-prod-by-420tiesto-killa-kam", platform: 'soundcloud' },
  { id: "drop-pin-ft-1takeocho-tyler-j", title: "Drop Pin FT 1takeocho Tyler J", url: "https://soundcloud.com/1takequan/drop-pin-ft-1takeocho-tyler-j", platform: 'soundcloud' },
  { id: "like-me-ft-1taketeezy-prod-by-mikeyy2yyz-jonnycash", title: "Like Me FT 1taketeezy PROD By Mikeyy2yyz Jonnycash", url: "https://soundcloud.com/1takequan/like-me-ft-1taketeezy-prod-by-mikeyy2yyz-jonnycash", platform: 'soundcloud' },
  { id: "too-much-prod-by-crook", title: "Too Much PROD By Crook", url: "https://soundcloud.com/1takequan/too-much-prod-by-crook", platform: 'soundcloud' },
  { id: "i-know-prod-by-acetheface", title: "I Know PROD By Acetheface", url: "https://soundcloud.com/1takequan/i-know-prod-by-acetheface", platform: 'soundcloud' },
  { id: "up-down-ft-tyler-j-prod-by-romo", title: "Up Down FT Tyler J PROD By Romo", url: "https://soundcloud.com/1takequan/up-down-ft-tyler-j-prod-by-romo", platform: 'soundcloud' },
  { id: "pop-that-prod-by-menanceonthebeat", title: "Pop That PROD By Menanceonthebeat", url: "https://soundcloud.com/1takequan/pop-that-prod-by-menanceonthebeat", platform: 'soundcloud' },
  { id: "in-love-again-prod-acetheface", title: "In Love Again PROD Acetheface", url: "https://soundcloud.com/1takequan/in-love-again-prod-acetheface", platform: 'soundcloud' },
  { id: "patience-prod-by-slapmafia", title: "Patience PROD By Slapmafia", url: "https://soundcloud.com/1takequan/patience-prod-by-slapmafia", platform: 'soundcloud' },
  { id: "talk-to-me-nice-ft-1takejay", title: "Talk To Me Nice FT 1takejay", url: "https://soundcloud.com/1takequan/talk-to-me-nice-ft-1takejay", platform: 'soundcloud' },
  { id: "my-way-prod-lowthegreat", title: "My Way PROD Lowthegreat", url: "https://soundcloud.com/1takequan/my-way-prod-lowthegreat", platform: 'soundcloud' },
  { id: "dont-play-prod-by-phoobear", title: "Dont Play PROD By Phoobear", url: "https://soundcloud.com/1takequan/dont-play-prod-by-phoobear", platform: 'soundcloud' },
  { id: "lethal-prod-by-slapmafia", title: "Lethal PROD By Slapmafia", url: "https://soundcloud.com/1takequan/lethal-prod-by-slapmafia", platform: 'soundcloud' },
  { id: "go-head-prodby-teezymaadeit-scumbeatz", title: "Go Head PRODBY Teezymaadeit Scumbeatz", url: "https://soundcloud.com/1takequan/go-head-prodby-teezymaadeit-scumbeatz", platform: 'soundcloud' },
  { id: "no-emotion", title: "No Emotion", url: "https://soundcloud.com/1takequan/no-emotion", platform: 'soundcloud' },
  { id: "when-you-come-over-prod-by-420tiesto-saltreze", title: "When You Come Over PROD By 420tiesto Saltreze", url: "https://soundcloud.com/1takequan/when-you-come-over-prod-by-420tiesto-saltreze", platform: 'soundcloud' },
  { id: "fight-the-pimpimg-freestyle-ft-pocaah", title: "Fight The Pimpimg Freestyle FT Pocaah", url: "https://soundcloud.com/1takequan/fight-the-pimpimg-freestyle-ft-pocaah", platform: 'soundcloud' },
  { id: "switch-lanes-prod-by-sneak-da-freak", title: "Switch Lanes PROD By Sneak Da Freak", url: "https://soundcloud.com/1takequan/switch-lanes-prod-by-sneak-da-freak", platform: 'soundcloud' },
  { id: "locked-in-prod-flyguyveezy", title: "Locked In PROD Flyguyveezy", url: "https://soundcloud.com/1takequan/locked-in-prod-flyguyveezy", platform: 'soundcloud' },
  { id: "adidas-sped-up-prod-by", title: "Adidas SPED Up PROD By", url: "https://soundcloud.com/1takequan/adidas-sped-up-prod-by", platform: 'soundcloud' },
  { id: "adidas-prod-slapmafia", title: "Adidas PROD Slapmafia", url: "https://soundcloud.com/1takequan/adidas-prod-slapmafia", platform: 'soundcloud' },
  { id: "on-the-road-ft-1taketeezy-bighube-prod-by-benny-ave", title: "On The Road FT 1taketeezy Bighube PROD By Benny Ave", url: "https://soundcloud.com/1takequan/on-the-road-ft-1taketeezy-bighube-prod-by-benny-ave", platform: 'soundcloud' },
  { id: "locksmith-ft-big-sad-1900-prod", title: "Locksmith FT Big Sad 1900 PROD", url: "https://soundcloud.com/1takequan/locksmith-ft-big-sad-1900-prod", platform: 'soundcloud' },
  { id: "on-the-wall-ft-pocaahontassss", title: "On The Wall FT Pocaahontassss", url: "https://soundcloud.com/1takequan/on-the-wall-ft-pocaahontassss", platform: 'soundcloud' },
  { id: "1942-prod-by-scum-uno", title: "1942 PROD By Scum Uno", url: "https://soundcloud.com/1takequan/1942-prod-by-scum-uno", platform: 'soundcloud' },
  { id: "drumroll-prod-by-teezymadeit", title: "Drumroll PROD By Teezymadeit", url: "https://soundcloud.com/1takequan/drumroll-prod-by-teezymadeit", platform: 'soundcloud' },
  { id: "one-call-prod-by-scum-uno-sped-up", title: "One Call PROD By Scum Uno SPED Up", url: "https://soundcloud.com/1takequan/one-call-prod-by-scum-uno-sped-up", platform: 'soundcloud' },
  { id: "one-call-prod-by-scum-uno", title: "One Call PROD By Scum Uno", url: "https://soundcloud.com/1takequan/one-call-prod-by-scum-uno", platform: 'soundcloud' },
  { id: "dna-ft-tylerj-chris-o-bannon-prod-by-romo", title: "Dna FT Tylerj Chris O Bannon PROD By Romo", url: "https://soundcloud.com/1takequan/dna-ft-tylerj-chris-o-bannon-prod-by-romo", platform: 'soundcloud' },
  { id: "feedback-prod-by-420tiesto", title: "Feedback PROD By 420tiesto", url: "https://soundcloud.com/1takequan/feedback-prod-by-420tiesto", platform: 'soundcloud' },
  { id: "fake-freaky-remix-ft-lil-vada", title: "Fake Freaky REMIX FT Lil Vada", url: "https://soundcloud.com/1takequan/fake-freaky-remix-ft-lil-vada", platform: 'soundcloud' },
  { id: "1takequan-campaign-prod-by", title: "1takequan Campaign PROD By", url: "https://soundcloud.com/1takequan/1takequan-campaign-prod-by", platform: 'soundcloud' },
  { id: "in-my-zone-prod-by", title: "In My Zone PROD By", url: "https://soundcloud.com/1takequan/in-my-zone-prod-by", platform: 'soundcloud' },
  { id: "1takequan-x-benny-ave-alone", title: "1takequan X Benny Ave Alone", url: "https://soundcloud.com/1takequan/1takequan-x-benny-ave-alone", platform: 'soundcloud' },
  { id: "1takequan-booted-up-ft", title: "1takequan Booted Up FT", url: "https://soundcloud.com/1takequan/1takequan-booted-up-ft", platform: 'soundcloud' },
  { id: "1taekequan-lil-shyt-prod-by", title: "1taekequan Lil Shyt PROD By", url: "https://soundcloud.com/1takequan/1taekequan-lil-shyt-prod-by", platform: 'soundcloud' },
  { id: "1takequan-lifestyle-ft-chxnk", title: "1takequan Lifestyle FT Chxnk", url: "https://soundcloud.com/1takequan/1takequan-lifestyle-ft-chxnk", platform: 'soundcloud' },
  { id: "1takequan-fake-freaky-prod-by", title: "1takequan Fake Freaky PROD By", url: "https://soundcloud.com/1takequan/1takequan-fake-freaky-prod-by", platform: 'soundcloud' },
  { id: "99-problems-prod-by", title: "99 Problems PROD By", url: "https://soundcloud.com/1takequan/99-problems-prod-by", platform: 'soundcloud' },
  { id: "bad-guy", title: "Bad Guy", url: "https://soundcloud.com/1takequan/bad-guy", platform: 'soundcloud' },
  { id: "tear-it-up-freestyle-prod-by-bennyave-420tiesto", title: "Tear It Up Freestyle PROD By Bennyave 420tiesto", url: "https://soundcloud.com/1takequan/tear-it-up-freestyle-prod-by-bennyave-420tiesto", platform: 'soundcloud' },
  { id: "call-this-prod-by-bennyave", title: "Call This PROD By Bennyave", url: "https://soundcloud.com/1takequan/call-this-prod-by-bennyave", platform: 'soundcloud' },
  { id: "nothing-less-ft-tyler-j-chris", title: "Nothing Less FT Tyler J Chris", url: "https://soundcloud.com/1takequan/nothing-less-ft-tyler-j-chris", platform: 'soundcloud' },
  { id: "1takequan-out-myne-prod-by", title: "1takequan Out Myne PROD By", url: "https://soundcloud.com/1takequan/1takequan-out-myne-prod-by", platform: 'soundcloud' },
  { id: "1takequan-ratchet-talk-prod-by", title: "1takequan Ratchet Talk PROD By", url: "https://soundcloud.com/1takequan/1takequan-ratchet-talk-prod-by", platform: 'soundcloud' },
  { id: "1takequan-hater-baby-prod-by", title: "1takequan Hater Baby PROD By", url: "https://soundcloud.com/1takequan/1takequan-hater-baby-prod-by", platform: 'soundcloud' },
  { id: "1takequan-do-dhat-prod-by", title: "1takequan Do Dhat PROD By", url: "https://soundcloud.com/1takequan/1takequan-do-dhat-prod-by", platform: 'soundcloud' },
  { id: "24a", title: "24a", url: "https://soundcloud.com/1takequan/24a", platform: 'soundcloud' },
  { id: "chitlins-feat-1takejay", title: "Chitlins FEAT 1takejay", url: "https://soundcloud.com/1takequan/chitlins-feat-1takejay", platform: 'soundcloud' },
  { id: "visions", title: "Visions", url: "https://soundcloud.com/1takequan/visions", platform: 'soundcloud' },
  { id: "damn-ant-feat-big-hube", title: "Damn Ant FEAT Big Hube", url: "https://soundcloud.com/1takequan/damn-ant-feat-big-hube", platform: 'soundcloud' },
  { id: "im-tripping-feat-rucci", title: "Im Tripping FEAT Rucci", url: "https://soundcloud.com/1takequan/im-tripping-feat-rucci", platform: 'soundcloud' },
  { id: "its-sum-feat-chxnk", title: "Its Sum FEAT Chxnk", url: "https://soundcloud.com/1takequan/its-sum-feat-chxnk", platform: 'soundcloud' },
  { id: "love-talk-feat-1takeocho-tyler-j", title: "Love Talk FEAT 1takeocho Tyler J", url: "https://soundcloud.com/1takequan/love-talk-feat-1takeocho-tyler-j", platform: 'soundcloud' },
  { id: "the-plan", title: "The Plan", url: "https://soundcloud.com/1takequan/the-plan", platform: 'soundcloud' },
  { id: "bubble-coat-feat-1taketeezy", title: "Bubble Coat FEAT 1taketeezy", url: "https://soundcloud.com/1takequan/bubble-coat-feat-1taketeezy", platform: 'soundcloud' },
  { id: "richard", title: "Richard", url: "https://soundcloud.com/1takequan/richard", platform: 'soundcloud' },
  { id: "lick-lick", title: "Lick Lick", url: "https://soundcloud.com/1takequan/lick-lick", platform: 'soundcloud' },
  { id: "1takequan-please-please-prod", title: "1takequan Please Please PROD", url: "https://soundcloud.com/1takequan/1takequan-please-please-prod", platform: 'soundcloud' },
  { id: "1takequan-timeless-prod-by", title: "1takequan Timeless PROD By", url: "https://soundcloud.com/1takequan/1takequan-timeless-prod-by", platform: 'soundcloud' },
  { id: "single", title: "Single", url: "https://soundcloud.com/1takequan/single", platform: 'soundcloud' },
  { id: "1takequan-jump-in-ft-almighty-suspect-1takejay", title: "1takequan Jump In FT Almighty Suspect 1takejay", url: "https://soundcloud.com/1takequan/1takequan-jump-in-ft-almighty-suspect-1takejay", platform: 'soundcloud' },
  { id: "eastside", title: "Eastside", url: "https://soundcloud.com/1takequan/eastside", platform: 'soundcloud' },
  { id: "hold-on-prod-by-adin", title: "Hold On PROD By Adin", url: "https://soundcloud.com/1takequan/hold-on-prod-by-adin", platform: 'soundcloud' },
  { id: "velveta-prod-micah-street", title: "Velveta PROD Micah Street", url: "https://soundcloud.com/1takequan/velveta-prod-micah-street", platform: 'soundcloud' },
  { id: "bankroll-prod-by-paupa", title: "Bankroll PROD By Paupa", url: "https://soundcloud.com/1takequan/bankroll-prod-by-paupa", platform: 'soundcloud' },
  { id: "bb-bottles-bitches-prod-by-mickey2yyz", title: "Bb Bottles Bitches PROD By Mickey2yyz", url: "https://soundcloud.com/1takequan/bb-bottles-bitches-prod-by-mickey2yyz", platform: 'soundcloud' },
  { id: "you-give-me-prod-by-benny-ave", title: "You Give Me PROD By Benny Ave", url: "https://soundcloud.com/1takequan/you-give-me-prod-by-benny-ave", platform: 'soundcloud' },
  { id: "do-they-work-prod-by-blizzy", title: "Do They Work PROD By Blizzy", url: "https://soundcloud.com/1takequan/do-they-work-prod-by-blizzy", platform: 'soundcloud' },
  { id: "swang-feat-cheif-boy-lee-lee-babi-prod-by-bigg-boo", title: "Swang FEAT Cheif Boy Lee Lee Babi PROD By Bigg Boo", url: "https://soundcloud.com/1takequan/swang-feat-cheif-boy-lee-lee-babi-prod-by-bigg-boo", platform: 'soundcloud' },
  { id: "jason-feat-1taketeezy-prod-by-romo", title: "Jason FEAT 1taketeezy PROD By Romo", url: "https://soundcloud.com/1takequan/jason-feat-1taketeezy-prod-by-romo", platform: 'soundcloud' },
  { id: "what-happened-feat-1takejay-prod-by-fads-bigg-boo", title: "What Happened FEAT 1takejay PROD By Fads Bigg Boo", url: "https://soundcloud.com/1takequan/what-happened-feat-1takejay-prod-by-fads-bigg-boo", platform: 'soundcloud' },
  { id: "man-down-feat-lil-duece", title: "Man Down FEAT Lil Duece", url: "https://soundcloud.com/1takequan/man-down-feat-lil-duece", platform: 'soundcloud' },
  { id: "confessions", title: "Confessions", url: "https://soundcloud.com/1takequan/confessions", platform: 'soundcloud' },
  { id: "backy-feat-1takejay-1taketeezy", title: "Backy FEAT 1takejay 1taketeezy", url: "https://soundcloud.com/1takequan/backy-feat-1takejay-1taketeezy", platform: 'soundcloud' },
  { id: "1takequan-ali-prod-by-zombie-sneekdafreek", title: "1takequan Ali PROD By Zombie Sneekdafreek", url: "https://soundcloud.com/1takequan/1takequan-ali-prod-by-zombie-sneekdafreek", platform: 'soundcloud' },
  { id: "1takequan-muslce-up-prod-by", title: "1takequan Muslce Up PROD By", url: "https://soundcloud.com/1takequan/1takequan-muslce-up-prod-by", platform: 'soundcloud' },
  { id: "wiggle-remix-ft-1takejay-prod-by-lowthegreat", title: "Wiggle REMIX FT 1takejay PROD By Lowthegreat", url: "https://soundcloud.com/1takequan/wiggle-remix-ft-1takejay-prod-by-lowthegreat", platform: 'soundcloud' },
  { id: "1takequan-fight-night-prod-by-lowthegreat", title: "1takequan Fight Night PROD By Lowthegreat", url: "https://soundcloud.com/1takequan/1takequan-fight-night-prod-by-lowthegreat", platform: 'soundcloud' },
  { id: "1takequan-ping-pong-prod-by", title: "1takequan Ping Pong PROD By", url: "https://soundcloud.com/1takequan/1takequan-ping-pong-prod-by", platform: 'soundcloud' },
  { id: "1takequan-booker-t-prod-by", title: "1takequan Booker T PROD By", url: "https://soundcloud.com/1takequan/1takequan-booker-t-prod-by", platform: 'soundcloud' },
  { id: "1takequan-wow-prod-by-bennyave", title: "1takequan Wow PROD By Bennyave", url: "https://soundcloud.com/1takequan/1takequan-wow-prod-by-bennyave", platform: 'soundcloud' },
  { id: "1takequan-go-girl-prod-by-1", title: "1takequan Go Girl PROD By", url: "https://soundcloud.com/1takequan/1takequan-go-girl-prod-by-1", platform: 'soundcloud' },
  { id: "1takequan-only-fans-prod-by-lowthegreat", title: "1takequan Only Fans PROD By Lowthegreat", url: "https://soundcloud.com/1takequan/1takequan-only-fans-prod-by-lowthegreat", platform: 'soundcloud' },
  { id: "1takequan-sex-prod-by", title: "1takequan Sex PROD By", url: "https://soundcloud.com/1takequan/1takequan-sex-prod-by", platform: 'soundcloud' },
  { id: "1takequan-mall-price-prod-by", title: "1takequan Mall Price PROD By", url: "https://soundcloud.com/1takequan/1takequan-mall-price-prod-by", platform: 'soundcloud' },
  { id: "1takequan-cap-prod-by-steelz", title: "1takequan Cap PROD By Steelz", url: "https://soundcloud.com/1takequan/1takequan-cap-prod-by-steelz", platform: 'soundcloud' },
  { id: "1takequan-i-love-it-ft-rucci-prod-by-biggboo", title: "1takequan I Love It FT Rucci PROD By Biggboo", url: "https://soundcloud.com/1takequan/1takequan-i-love-it-ft-rucci-prod-by-biggboo", platform: 'soundcloud' },
  { id: "1takequan-back-then-ft-mister", title: "1takequan Back Then FT Mister", url: "https://soundcloud.com/1takequan/1takequan-back-then-ft-mister", platform: 'soundcloud' },
  { id: "1takequan-faded-down-prod-by-dtscurt", title: "1takequan Faded Down PROD By Dtscurt", url: "https://soundcloud.com/1takequan/1takequan-faded-down-prod-by-dtscurt", platform: 'soundcloud' },
  { id: "1takequan-big-dog-prod-by", title: "1takequan Big Dog PROD By", url: "https://soundcloud.com/1takequan/1takequan-big-dog-prod-by", platform: 'soundcloud' },
  { id: "1takequan-no-cut-prod-by-jv", title: "1takequan No Cut PROD By Jv", url: "https://soundcloud.com/1takequan/1takequan-no-cut-prod-by-jv", platform: 'soundcloud' },
  { id: "1takequan-plumber-prod-by", title: "1takequan Plumber PROD By", url: "https://soundcloud.com/1takequan/1takequan-plumber-prod-by", platform: 'soundcloud' },
  { id: "1takequan-fbgm-prod-by", title: "1takequan Fbgm PROD By", url: "https://soundcloud.com/1takequan/1takequan-fbgm-prod-by", platform: 'soundcloud' },
  { id: "1takequan-instructions-prod-by", title: "1takequan Instructions PROD By", url: "https://soundcloud.com/1takequan/1takequan-instructions-prod-by", platform: 'soundcloud' },
  { id: "1takequan-jerry-rice-prod-by", title: "1takequan Jerry Rice PROD By", url: "https://soundcloud.com/1takequan/1takequan-jerry-rice-prod-by", platform: 'soundcloud' },
  { id: "1takequan-shots-prod-by", title: "1takequan Shots PROD By", url: "https://soundcloud.com/1takequan/1takequan-shots-prod-by", platform: 'soundcloud' },
  { id: "1takequan-wiggle-prod-by-lowthegreat", title: "1takequan Wiggle PROD By Lowthegreat", url: "https://soundcloud.com/1takequan/1takequan-wiggle-prod-by-lowthegreat", platform: 'soundcloud' },
  { id: "1takequan-double-f-prod-by-lowthegreat", title: "1takequan Double F PROD By Lowthegreat", url: "https://soundcloud.com/1takequan/1takequan-double-f-prod-by-lowthegreat", platform: 'soundcloud' },
  { id: "1takequan-chris-obannon-on", title: "1takequan Chris Obannon On", url: "https://soundcloud.com/1takequan/1takequan-chris-obannon-on", platform: 'soundcloud' },
  { id: "1takequan-chris-obannon-my", title: "1takequan Chris Obannon My", url: "https://soundcloud.com/1takequan/1takequan-chris-obannon-my", platform: 'soundcloud' },
  { id: "1takequan-chris-obannon", title: "1takequan Chris Obannon", url: "https://soundcloud.com/1takequan/1takequan-chris-obannon", platform: 'soundcloud' },
  { id: "1takequan-chris-obannon-stingy", title: "1takequan Chris Obannon Stingy", url: "https://soundcloud.com/1takequan/1takequan-chris-obannon-stingy", platform: 'soundcloud' },
  { id: "1takequan-chris-obannon-talk", title: "1takequan Chris Obannon Talk", url: "https://soundcloud.com/1takequan/1takequan-chris-obannon-talk", platform: 'soundcloud' },
  { id: "uan-x-1takejay-mf-prod", title: "Uan X 1takejay Mf PROD", url: "https://soundcloud.com/1takequan/uan-x-1takejay-mf-prod", platform: 'soundcloud' },
  { id: "1takequan-homi-prod-by-scumbeats", title: "1takequan Homi PROD By Scumbeats", url: "https://soundcloud.com/1takequan/1takequan-homi-prod-by-scumbeats", platform: 'soundcloud' },
  { id: "all-blues-feat-azchike-x-bravo-the-bagchaserprod-by-scum-beats-x-flashassuno-x-laudiano", title: "All Blues FEAT Azchike X Bravo The Bagchaserprod By Scum Beats X Flashassuno X Laudiano", url: "https://soundcloud.com/1takequan/all-blues-feat-azchike-x-bravo-the-bagchaserprod-by-scum-beats-x-flashassuno-x-laudiano", platform: 'soundcloud' },
  { id: "sus-quan-macho", title: "Sus Quan Macho", url: "https://soundcloud.com/1takequan/sus-quan-macho", platform: 'soundcloud' },
  { id: "freak-feat-kalan-frfr", title: "Freak FEAT Kalan Frfr", url: "https://soundcloud.com/1takequan/freak-feat-kalan-frfr", platform: 'soundcloud' },
  { id: "1takequan-diffrent-vibe-prod", title: "1takequan Diffrent Vibe PROD", url: "https://soundcloud.com/1takequan/1takequan-diffrent-vibe-prod", platform: 'soundcloud' },
  { id: "1takequan-lil-shawty-prod-by", title: "1takequan Lil Shawty PROD By", url: "https://soundcloud.com/1takequan/1takequan-lil-shawty-prod-by", platform: 'soundcloud' },
  { id: "1takequan-perfect-timing-prod", title: "1takequan Perfect Timing PROD", url: "https://soundcloud.com/1takequan/1takequan-perfect-timing-prod", platform: 'soundcloud' },
  { id: "1takequan-simple-prod-by", title: "1takequan Simple PROD By", url: "https://soundcloud.com/1takequan/1takequan-simple-prod-by", platform: 'soundcloud' },
  { id: "1takequan-prize", title: "1takequan Prize", url: "https://soundcloud.com/1takequan/1takequan-prize", platform: 'soundcloud' },
  { id: "1takequan-the-night-prod-by", title: "1takequan The Night PROD By", url: "https://soundcloud.com/1takequan/1takequan-the-night-prod-by", platform: 'soundcloud' },
  { id: "1takequan-x-jstar-questions", title: "1takequan X Jstar Questions", url: "https://soundcloud.com/1takequan/1takequan-x-jstar-questions", platform: 'soundcloud' },
  { id: "1takequan-x-rucci-fresh-prince-prod-by-420tiesto", title: "1takequan X Rucci Fresh Prince PROD By 420tiesto", url: "https://soundcloud.com/1takequan/1takequan-x-rucci-fresh-prince-prod-by-420tiesto", platform: 'soundcloud' },
  { id: "1takequan-never-slip-prod-by-420tiesto", title: "1takequan Never Slip PROD By 420tiesto", url: "https://soundcloud.com/1takequan/1takequan-never-slip-prod-by-420tiesto", platform: 'soundcloud' },
  { id: "1takequan-fuego-prod-by-djtray", title: "1takequan Fuego PROD By Djtray", url: "https://soundcloud.com/1takequan/1takequan-fuego-prod-by-djtray", platform: 'soundcloud' },
  { id: "middle-fingers", title: "Middle Fingers", url: "https://soundcloud.com/1takequan/middle-fingers", platform: 'soundcloud' },
  { id: "burnt", title: "Burnt", url: "https://soundcloud.com/1takequan/burnt", platform: 'soundcloud' },
  { id: "expensive-habits", title: "Expensive Habits", url: "https://soundcloud.com/1takequan/expensive-habits", platform: 'soundcloud' },
  { id: "memorized", title: "Memorized", url: "https://soundcloud.com/1takequan/memorized", platform: 'soundcloud' },
  { id: "1000-bubbles", title: "1000 Bubbles", url: "https://soundcloud.com/1takequan/1000-bubbles", platform: 'soundcloud' },
  { id: "flavor", title: "Flavor", url: "https://soundcloud.com/1takequan/flavor", platform: 'soundcloud' },
  { id: "demons", title: "Demons", url: "https://soundcloud.com/1takequan/demons", platform: 'soundcloud' },
  { id: "wwyt", title: "Wwyt", url: "https://soundcloud.com/1takequan/wwyt", platform: 'soundcloud' },
  { id: "go-gettah", title: "Go Gettah", url: "https://soundcloud.com/1takequan/go-gettah", platform: 'soundcloud' },
  { id: "ah-need-prod-by-sorryjaynari", title: "Ah Need PROD By Sorryjaynari", url: "https://soundcloud.com/1takequan/ah-need-prod-by-sorryjaynari", platform: 'soundcloud' },
  { id: "hit-baby-prod-by-meez-louieji", title: "Hit Baby PROD By Meez Louieji", url: "https://soundcloud.com/1takequan/hit-baby-prod-by-meez-louieji", platform: 'soundcloud' },
  { id: "everything-new-prod-by", title: "Everything New PROD By", url: "https://soundcloud.com/1takequan/everything-new-prod-by", platform: 'soundcloud' },
  { id: "stay-drunk-feat-lowthegreat", title: "Stay Drunk FEAT Lowthegreat", url: "https://soundcloud.com/1takequan/stay-drunk-feat-lowthegreat", platform: 'soundcloud' },
  { id: "ya-feel-me-prod-by-meez", title: "Ya Feel Me PROD By Meez", url: "https://soundcloud.com/1takequan/ya-feel-me-prod-by-meez", platform: 'soundcloud' },
  { id: "top-5-prod-by-mikeyy2yz", title: "Top 5 PROD By Mikeyy2yz", url: "https://soundcloud.com/1takequan/top-5-prod-by-mikeyy2yz", platform: 'soundcloud' },
  { id: "loss-prod-by-420tiesto", title: "Loss PROD By 420tiesto", url: "https://soundcloud.com/1takequan/loss-prod-by-420tiesto", platform: 'soundcloud' },
  { id: "i-like-prod-by-420tiesto", title: "I Like PROD By 420tiesto", url: "https://soundcloud.com/1takequan/i-like-prod-by-420tiesto", platform: 'soundcloud' },
  { id: "dont-hurt-nobody-prod-by", title: "Dont Hurt Nobody PROD By", url: "https://soundcloud.com/1takequan/dont-hurt-nobody-prod-by", platform: 'soundcloud' },
  { id: "loser-prod-by-420tiesto", title: "Loser PROD By 420tiesto", url: "https://soundcloud.com/1takequan/loser-prod-by-420tiesto", platform: 'soundcloud' },
  { id: "1-2-3-prod-by-420tiesto", title: "1 2 3 PROD By 420tiesto", url: "https://soundcloud.com/1takequan/1-2-3-prod-by-420tiesto", platform: 'soundcloud' },
  { id: "money-prod-by-420tiesto", title: "Money PROD By 420tiesto", url: "https://soundcloud.com/1takequan/money-prod-by-420tiesto", platform: 'soundcloud' },
  { id: "1takequan-longtime-ft-daidmb-prod-by-paupa", title: "1takequan Longtime FT Daidmb PROD By Paupa", url: "https://soundcloud.com/1takequan/1takequan-longtime-ft-daidmb-prod-by-paupa", platform: 'soundcloud' },
  { id: "1takequan-x-gogettahkb-18dummy-prod-by-paupa", title: "1takequan X Gogettahkb 18dummy PROD By Paupa", url: "https://soundcloud.com/1takequan/1takequan-x-gogettahkb-18dummy-prod-by-paupa", platform: 'soundcloud' },
  { id: "1takequan-fuck-it-up-radio-edit-master", title: "1takequan Fuck It Up RADIO EDIT MASTER", url: "https://soundcloud.com/1takequan/1takequan-fuck-it-up-radio-edit-master", platform: 'soundcloud' },
  { id: "1takequan-dont-stop-prod-by-420tiesto", title: "1takequan Dont Stop PROD By 420tiesto", url: "https://soundcloud.com/1takequan/1takequan-dont-stop-prod-by-420tiesto", platform: 'soundcloud' },
  { id: "1takequan-savages-ft-ashbashtharapper-prod-by-kingxriko", title: "1takequan Savages FT Ashbashtharapper PROD By Kingxriko", url: "https://soundcloud.com/1takequan/1takequan-savages-ft-ashbashtharapper-prod-by-kingxriko", platform: 'soundcloud' },
  { id: "1takequan-1take-slide-prod-by-arjayonthebeat", title: "1takequan 1take Slide PROD By Arjayonthebeat", url: "https://soundcloud.com/1takequan/1takequan-1take-slide-prod-by-arjayonthebeat", platform: 'soundcloud' },
  { id: "go-to-work-feat-dmb-gotti", title: "Go To Work FEAT Dmb Gotti", url: "https://soundcloud.com/1takequan/go-to-work-feat-dmb-gotti", platform: 'soundcloud' },
  { id: "say-so-feat-1taketeezy-kalan", title: "Say So FEAT 1taketeezy Kalan", url: "https://soundcloud.com/1takequan/say-so-feat-1taketeezy-kalan", platform: 'soundcloud' },
  { id: "weird-shit", title: "Weird Shit", url: "https://soundcloud.com/1takequan/weird-shit", platform: 'soundcloud' },
  { id: "2019", title: "2019", url: "https://soundcloud.com/1takequan/2019", platform: 'soundcloud' },
  { id: "bopper", title: "Bopper", url: "https://soundcloud.com/1takequan/bopper", platform: 'soundcloud' },
  { id: "savages", title: "Savages", url: "https://soundcloud.com/1takequan/savages", platform: 'soundcloud' },
  { id: "who-want-it", title: "Who Want It", url: "https://soundcloud.com/1takequan/who-want-it", platform: 'soundcloud' },
  { id: "closer-to-you-feat-1takeocho", title: "Closer To You FEAT 1takeocho", url: "https://soundcloud.com/1takequan/closer-to-you-feat-1takeocho", platform: 'soundcloud' },
  { id: "call-her-a-bitch-freestyle", title: "Call Her A Bitch Freestyle", url: "https://soundcloud.com/1takequan/call-her-a-bitch-freestyle", platform: 'soundcloud' },
  { id: "long-time", title: "Long Time", url: "https://soundcloud.com/1takequan/long-time", platform: 'soundcloud' },
  { id: "yeah-dat", title: "Yeah Dat", url: "https://soundcloud.com/1takequan/yeah-dat", platform: 'soundcloud' },
  { id: "new-olympics", title: "New Olympics", url: "https://soundcloud.com/1takequan/new-olympics", platform: 'soundcloud' },
  { id: "grub-hub", title: "Grub Hub", url: "https://soundcloud.com/1takequan/grub-hub", platform: 'soundcloud' },
  { id: "now-drop-freestyle", title: "Now Drop Freestyle", url: "https://soundcloud.com/1takequan/now-drop-freestyle", platform: 'soundcloud' },
  { id: "feel-special-feat-j-star", title: "Feel Special FEAT J Star", url: "https://soundcloud.com/1takequan/feel-special-feat-j-star", platform: 'soundcloud' },
  { id: "focused", title: "Focused", url: "https://soundcloud.com/1takequan/focused", platform: 'soundcloud' },
  { id: "most-likely-feat-hube", title: "Most Likely FEAT Hube", url: "https://soundcloud.com/1takequan/most-likely-feat-hube", platform: 'soundcloud' },
  { id: "pretty-brown", title: "Pretty Brown", url: "https://soundcloud.com/1takequan/pretty-brown", platform: 'soundcloud' },
  { id: "my-lady", title: "My Lady", url: "https://soundcloud.com/1takequan/my-lady", platform: 'soundcloud' },
  { id: "sinkin", title: "Sinkin", url: "https://soundcloud.com/1takequan/sinkin", platform: 'soundcloud' },
  { id: "like-this-feat-tony-heisman", title: "Like This FEAT Tony Heisman", url: "https://soundcloud.com/1takequan/like-this-feat-tony-heisman", platform: 'soundcloud' },
];
